
class WindowUtils:
    def testfunc(self) -> int:...
    def ForceForegroundWindow(self, pid: int) -> None:...
    def GetWindowName(self, pid: int) -> str:...
    def GetActiveProcess(self) -> int:...


class ClickUtils:

    def ClickBackgroundWindow(self, pid: int, click_type: str) -> None:...

    def ClickBackgroundWindowPosition(self, pid: int, x: int, y: int, click_type: str) -> None:...

    def ClickWindowPositionFocusSwitch(self, pid: int, x: int, y: int, click_type: str) -> None:...