
class WindowUtils:
    def testfunc(self) -> int:...
    def ForceForegroundWindow(self, pid: int) -> None:...
    def GetWindowName(self, pid: int) -> str:...
    def GetActiveProcess(self) -> int:...
